export {
  HIT_FEEDBACK_DURATION_MS,
  VK_APP_ID,
  VK_APP_URL,
  createPlatformAdapter,
  detectVkLaunchContext,
  type PlatformAdapter,
  type PlatformAdapterOptions,
  type PlatformDocument,
  type PlatformKind,
  type PlatformLifecycleHandlers,
  type PlatformNavigator,
  type PlatformWindow,
  type VkBridgeEvent,
  type VkBridgeLike,
  type VkBridgeListener,
  type VkLaunchContext,
} from "./PlatformAdapter";
